/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    IconTheme: typeof import('./src/components/IconTheme.vue')['default']
    INotoMoon: typeof import('~icons/noto/moon')['default']
    INotoSMoon: typeof import('~icons/noto/s-moon')['default']
    INotoSunWithFace: typeof import('~icons/noto/sun-with-face')['default']
    IUilMinus: typeof import('~icons/uil/minus')['default']
    IUilMinusCircle: typeof import('~icons/uil/minus-circle')['default']
    IUilMoon: typeof import('~icons/uil/moon')['default']
    IUilSquare: typeof import('~icons/uil/square')['default']
    IUilSquareShape: typeof import('~icons/uil/square-shape')['default']
    IUilSun: typeof import('~icons/uil/sun')['default']
    IUilTimes: typeof import('~icons/uil/times')['default']
    IUilTimesCircle: typeof import('~icons/uil/times-circle')['default']
    LayoutHeader: typeof import('./src/components/LayoutHeader.vue')['default']
    LayoutMain: typeof import('./src/components/LayoutMain.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NElement: typeof import('naive-ui')['NElement']
    NIcon: typeof import('naive-ui')['NIcon']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NR: typeof import('naive-ui')['NR']
    NSwitch: typeof import('naive-ui')['NSwitch']
    PageHome: typeof import('./src/components/PageHome.vue')['default']
    PageTwo: typeof import('./src/components/PageTwo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Versions: typeof import('./src/components/Versions.vue')['default']
  }
}
